val businessFile=sc.textFile("/user/brk160030/business.csv")
val reviewFile=sc.textFile("/user/brk160030/review.csv")
val stanfordData=businessFile.map(line=>line.split("\\::")).filter(line=>line(1).contains("Stanford")).map(line=>(line(0)))
val splitReviewData=reviewFile.map(line=>line.split("\\::")).map(line=>(line(1),line(2),line(3)))
val businessDataFrame=stanfordData.toDF("businessid")
val reviewDataFrame=splitReviewData.toDF("userid","businessid","stars")
val output=reviewDataFrame.join(businessDataFrame,"businessid").distinct().select("userid","stars").map(line=>line(0)+"\t\t"+line(1))
output.collect.foreach(println)
output.repartition(1).saveAsTextFile("/user/brk160030/output1")
